import { prisma } from '../src/lib/prisma'

const PRICING_SEED = [
  // TV
  {
    categoryId: 'tv',
    category: 'LED / Smart TV',
    name: 'Doorstep TV Diagnosis & Inspection',
    priceRange: '₹299',
    serviceTime: '45–60 Mins',
    popular: false,
    description: 'Complete board-level testing, power supply voltage verification & panel health check.',
    features: JSON.stringify(['100% adjusted in repair bill', 'On-site fault detection', 'Written quote before repair']),
    sortOrder: 1,
  },
  {
    categoryId: 'tv',
    category: 'LED / Smart TV',
    name: 'LED Backlight Array Replacement',
    priceRange: '₹899 – ₹1,899',
    serviceTime: 'Same Day',
    popular: true,
    description: 'Fixes dark screen, sound working but no display, flickering or dim patches on display.',
    features: JSON.stringify(['Full genuine LED strip set', 'Even brightness calibration', '90-day parts warranty']),
    sortOrder: 2,
  },
  {
    categoryId: 'tv',
    category: 'LED / Smart TV',
    name: 'Power Supply Board Repair',
    priceRange: '₹699 – ₹1,499',
    serviceTime: 'Same Day',
    popular: false,
    description: 'Resolves TV dead condition, red standby light blinking, or sudden power shut-offs.',
    features: JSON.stringify(['SMD component replacement', 'Surge protection check', '30-day service warranty']),
    sortOrder: 3,
  },
  {
    categoryId: 'tv',
    category: 'LED / Smart TV',
    name: 'Motherboard / Logic Card Repair',
    priceRange: '₹1,199 – ₹2,499',
    serviceTime: '24–48 Hrs',
    popular: false,
    description: 'Fixes logo hanging, HDMI/WiFi port failure, boot-loop, or software firmware crash.',
    features: JSON.stringify(['Micro-soldering diagnostics', 'Firmware reprogramming', 'Component-level repair']),
    sortOrder: 4,
  },
  {
    categoryId: 'tv',
    category: 'LED / Smart TV',
    name: 'TV Audio / Speaker Repair',
    priceRange: '₹549 – ₹999',
    serviceTime: 'Same Day',
    popular: false,
    description: 'Fixes cracked sound, distorted audio, or zero volume output from TV speakers.',
    features: JSON.stringify(['Dual speaker replacement', 'Audio IC check', '30-day warranty']),
    sortOrder: 5,
  },
  {
    categoryId: 'tv',
    category: 'LED / Smart TV',
    name: 'Wall Mount & Uninstallation',
    priceRange: '₹399 – ₹699',
    serviceTime: '45 Mins',
    popular: false,
    description: 'Heavy-duty swivel or fixed bracket installation with precision spirit-level alignment.',
    features: JSON.stringify(['Standard/heavy mount included', 'Concealed wiring advice', 'Zero wall damage guarantee']),
    sortOrder: 6,
  },
  // Refrigerator
  {
    categoryId: 'refrigerator',
    category: 'Refrigerator',
    name: 'Doorstep Fridge Inspection Visit',
    priceRange: '₹299',
    serviceTime: '45–60 Mins',
    popular: false,
    description: 'Comprehensive cooling test, thermostat calibration & compressor amp-load check.',
    features: JSON.stringify(['Adjusted against total bill', 'Doorstep testing', 'Honest fault report']),
    sortOrder: 1,
  },
  {
    categoryId: 'refrigerator',
    category: 'Refrigerator',
    name: 'Full Gas Refilling (R600a / R134a)',
    priceRange: '₹1,499 – ₹2,299',
    serviceTime: 'Same Day',
    popular: true,
    description: 'Complete nitrogen pressure leak detection, copper brazing, vacuuming & gas charging.',
    features: JSON.stringify(['Pure grade refrigerant', 'Leak seal & test', '60-day cooling warranty']),
    sortOrder: 2,
  },
  {
    categoryId: 'refrigerator',
    category: 'Refrigerator',
    name: 'Thermostat & Cooling Sensor Repair',
    priceRange: '₹499 – ₹999',
    serviceTime: 'Same Day',
    popular: false,
    description: 'Solves excess ice formation, low cooling in lower chamber, or continuous running.',
    features: JSON.stringify(['OEM grade thermostat', 'Bimetal sensor check', 'Temperature tuning']),
    sortOrder: 3,
  },
  {
    categoryId: 'refrigerator',
    category: 'Refrigerator',
    name: 'Relay, Overload Protector & Capacitor',
    priceRange: '₹449 – ₹899',
    serviceTime: 'Same Day',
    popular: false,
    description: 'Fixes humming noise, clicking compressor restart sounds, or fridge tripping MCB.',
    features: JSON.stringify(['High-durability starter relay', 'PTC component testing', '30-day warranty']),
    sortOrder: 4,
  },
  {
    categoryId: 'refrigerator',
    category: 'Refrigerator',
    name: 'Inverter Compressor Diagnostics & PCB',
    priceRange: '₹1,899 – ₹3,499',
    serviceTime: 'Same Day / 24 Hrs',
    popular: false,
    description: 'Inverter compressor board troubleshooting and certified motor drive repair.',
    features: JSON.stringify(['Inverter PCB diagnostics', 'Genuine replacement spares', '90-day warranty']),
    sortOrder: 5,
  },
  // Washing Machine
  {
    categoryId: 'washing-machine',
    category: 'Washing Machine',
    name: 'Doorstep Washing Machine Inspection',
    priceRange: '₹299',
    serviceTime: '45–60 Mins',
    popular: false,
    description: 'Check drum rotation, motor torque, inlet valves, drain pump & error code scan.',
    features: JSON.stringify(['Adjusted against repair', 'Error code clearance', 'Doorstep diagnostics']),
    sortOrder: 1,
  },
  {
    categoryId: 'washing-machine',
    category: 'Washing Machine',
    name: 'Drain Pump Repair & Blockage Removal',
    priceRange: '₹449 – ₹899',
    serviceTime: 'Same Day',
    popular: true,
    description: 'Solves water retention, OE error codes, slow draining, or pump motor humming.',
    features: JSON.stringify(['Filter descaling', 'High-flow replacement pump', '30-day warranty']),
    sortOrder: 2,
  },
  {
    categoryId: 'washing-machine',
    category: 'Washing Machine',
    name: 'Spin Dryer & Drive Belt Repair',
    priceRange: '₹499 – ₹1,099',
    serviceTime: 'Same Day',
    popular: false,
    description: 'Fixes clothes coming out soaking wet, drum not spinning, or burning rubber smell.',
    features: JSON.stringify(['Heavy-duty drive belt', 'Clutch spring test', 'Vibration reduction']),
    sortOrder: 3,
  },
  {
    categoryId: 'washing-machine',
    category: 'Washing Machine',
    name: 'Tub Bearing & Spider Arm Repair',
    priceRange: '₹1,199 – ₹2,199',
    serviceTime: '24–48 Hrs',
    popular: false,
    description: 'Eliminates loud metallic grinding noise, violent drum shaking during high RPM spin.',
    features: JSON.stringify(['High-grade sealed bearings', 'Drum realignment', '60-day warranty']),
    sortOrder: 4,
  },
  {
    categoryId: 'washing-machine',
    category: 'Washing Machine',
    name: 'Electronic Control PCB Repair',
    priceRange: '₹1,199 – ₹2,499',
    serviceTime: '24–48 Hrs',
    popular: false,
    description: 'Fixes display blanking, touch buttons not responding, or sudden cycle pause.',
    features: JSON.stringify(['Micro-relay replacement', 'Moisture sealing', '30-day warranty']),
    sortOrder: 5,
  },
  // AC
  {
    categoryId: 'ac',
    category: 'Air Conditioner (AC)',
    name: 'Deep Foam Chemical Jet Servicing',
    priceRange: '₹499 – ₹799',
    serviceTime: '45–60 Mins',
    popular: true,
    description: 'High-pressure water pump wash for cooling fins, blower fan, drain tray & condenser.',
    features: JSON.stringify(['Anti-bacterial foam spray', 'Filter & fin cleaning', 'Airflow & cooling boost']),
    sortOrder: 1,
  },
  {
    categoryId: 'ac',
    category: 'Air Conditioner (AC)',
    name: 'AC Gas Charging & Leak Brazing',
    priceRange: '₹1,699 – ₹2,499',
    serviceTime: 'Same Day',
    popular: false,
    description: 'Full nitrogen pressure testing, flare nut brazing, vacuuming & gas charging (R32/R410A).',
    features: JSON.stringify(['100% pure refrigerant', 'Leak proof warranty', 'Coil pressure test']),
    sortOrder: 2,
  },
  {
    categoryId: 'ac',
    category: 'Air Conditioner (AC)',
    name: 'Capacitor & Fan Motor Replacement',
    priceRange: '₹599 – ₹1,299',
    serviceTime: 'Same Day',
    popular: false,
    description: 'Resolves indoor/outdoor fan not running, low breeze, or compressor not starting.',
    features: JSON.stringify(['Heavy-duty dual capacitor', 'Motor winding test', '30-day warranty']),
    sortOrder: 3,
  },
  {
    categoryId: 'ac',
    category: 'Air Conditioner (AC)',
    name: 'Split AC Installation / Uninstallation',
    priceRange: '₹799 – ₹1,499',
    serviceTime: '60–90 Mins',
    popular: false,
    description: 'Professional bracket mounting, copper pipe flare connection & vacuum pump testing.',
    features: JSON.stringify(['Vibration pads included', 'Level balanced mounting', 'Zero gas leak test']),
    sortOrder: 4,
  },
  // Others
  {
    categoryId: 'others',
    category: 'Microwave & Other Appliances',
    name: 'Microwave Heating / Magnetron Repair',
    priceRange: '₹699 – ₹1,499',
    serviceTime: 'Same Day',
    popular: true,
    description: 'Fixes microwave turning on and spinning but not heating food at all.',
    features: JSON.stringify(['Magnetron tube test', 'High-voltage diode check', 'Safety radiation seal']),
    sortOrder: 1,
  },
  {
    categoryId: 'others',
    category: 'Microwave & Other Appliances',
    name: 'Microwave Touchpad & Button Repair',
    priceRange: '₹499 – ₹999',
    serviceTime: 'Same Day',
    popular: false,
    description: 'Fixes un-responsive start button, touch membrane failure, or timer glitch.',
    features: JSON.stringify(['Membrane keypad repair', 'Micro-switch service', '30-day warranty']),
    sortOrder: 2,
  },
  {
    categoryId: 'others',
    category: 'Microwave & Other Appliances',
    name: 'Geyser Element & Thermostat Repair',
    priceRange: '₹599 – ₹1,199',
    serviceTime: 'Same Day',
    popular: false,
    description: 'Solves water not heating, tripping circuit breaker, or scale deposition.',
    features: JSON.stringify(['Heavy copper heating element', 'Auto-cutoff thermostat', 'Leakage seal']),
    sortOrder: 3,
  },
  {
    categoryId: 'others',
    category: 'Microwave & Other Appliances',
    name: 'RO Water Purifier Full Service & Filters',
    priceRange: '₹499 – ₹1,399',
    serviceTime: 'Same Day',
    popular: false,
    description: 'Sediment, pre-carbon, post-carbon filter replacement & TDS water purity tuning.',
    features: JSON.stringify(['Certified filter kit', 'Membrane flushing', 'TDS water quality check']),
    sortOrder: 4,
  },
]

async function seed() {
  const count = await prisma.pricingItem.count()
  if (count > 0) {
    console.log(`Database already has ${count} pricing items. Skipping seed.`)
    return
  }

  for (const item of PRICING_SEED) {
    await prisma.pricingItem.create({ data: item })
  }
  console.log(`Successfully seeded ${PRICING_SEED.length} pricing items into database!`)
}

seed()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
